### PR TITLE
[#31] [#30] Implement async onEnter/Exit; default to true if the return value is undefined

### LINKED ISSUE #30: Support async transition
It is very good library, but i need to have more powrful control on function:

````
onEnter(state: T, callback: (from?: T, event?: any) => boolean): FiniteStateMachine<T>;
````

It is very good to be: 
````
type SyncFunction = callback: (from?: T, event?: any) => boolean 
Type AsyncFunction =  callback: (from?: T, event?: any) => Promise<boolean> 
onEnter(state: T, callback: SyncFunction | AsyncFunction  ): FiniteStateMachine<T>

````

### LINKED ISSUE #31: onEnter default return value to true
`onEnter` expects a boolean return value. If it's `false`, TypeState does not enter the state. If it's `true` TypeState enters the state.

However, if it's `undefined`, which happens if the user simply didn't return anything, TypeState will interpret it as `false` and thus, not enter the state. This is usually not what the user intended to happen.

Example:
```typescript
fsm.onEnter(Elevator.DoorsClosed, (from: Elevator)=>{
   setupGroovyElevatorMusic();
   // Since this doesn't return true, the doors will never close
});
```

My suggestion would be to default to `true` if the return value is `undefined`. However, in some cases this could also result in undesired behaviour.

### PR DESCRIPTION
**Pull request by stefnotch**
Fixes #31 and fixes #30

### CODE REVIEW

**Comment by eonarheim** [comment]
@stefnotch The typescript compiler lib options need to be updated to include promises to fix the build

**Comment by stefnotch** [comment]
Oh, sorry. My bad.

Speaking of issues, I should probably also write some unit tests. I'll be closing this PR for now.

**Comment by stefnotch** [comment]
I added unit tests and fixed a number of issues with my code that I ended up noticing.

**Comment by eonarheim** [comment]
@stefnotch I'll release a new version of TypeState on npm as soon as I can.

**Pull request merged**
